modLoader="javafml"
loaderVersion="[4,)"
mixinConfig="commhub.mixins.json"
license="MIT"

[[mods]]
modId="commhub"
version="1.11.44"
displayName="mcmcp的仓库"
description='''一键仓库：私聊、传物品、共享大仓库与私人命名仓库、以物换物。'''
authors=["mcmcp"]

[[dependencies.commhub]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.commhub]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
